In [94]:
import os
import numpy as np
import pandas as pd
import matplotlib as mpl
from scipy.stats import t, norm
import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer
import statsmodels.api as sm


fpath = 'C:/Users/becha/Desktop/Item_analysis/Data'

# Data

In [131]:
# load datas 
data = pd.read_csv((os.path.join(fpath, 'preprocessed.csv')))

In [132]:
data

,number,1,2,3,4,5,6,7,8,9,...,272,273,274,275,276,277,278,279,280,281
0,gender,female,male,male,female,male,female,female,female,male,...,female,male,female,nonbinary,male,male,female,female,female,male
1,Q1,3,3,2,3,4,3,4,3,1,...,5,4,NaN,4,5,4,4,5,3,4
2,Q2,6,5,5,6,5,5,5,6,4,...,5,6,4,5,4,6,4,5,6,6
3,Q3,6,5,5,6,5,5,4,6,5,...,6,6,5,5,2,5,5,6,5,6
4,Q4,6,5,5,6,5,4,5,6,5,...,6,6,6,6,2,6,6,6,6,6
5,Q5,6,5,5,6,6,5,4,6,5,...,6,6,4,6,6,6,5,5,5,6
6,Q6,6,4,5,5,4,5,4,6,2,...,6,6,5,5,6,6,5,4,6,6
7,Q7,4,4,4,3,3,5,4,1,1,...,5,3,4,4,5,4,4,2,3,6
8,Q8,6,2,4,5,4,4,4,1,1,...,4,3,5,4,5,3,3,2,4,3
9,Q9,6,5,4,5,3,4,4,6,2,...,5,5,4,3,4,6,5,4,5,6
10,Q10,6,4,5,6,4,4,5,4,NaN,...,5,3,5,5,NaN,5,6,6,6,6
11,Q11,6,3,4,5,5,3,4,4,5,...,4,NaN,NaN,5,6,2,5,NaN,5,3
12,Q12,6,3,5,6,5,5,5,4,5,...,6,6,5,5,5,5,5,6,6,6
13,Q13,6,5,5,5,5,5,4,6,5,...,5,6,5,6,6,6,5,6,6,6
14,Q14,6,5,5,5,5,5,5,6,6,...,6,6,6,6,6,4,5,6,6,6
15,Q15,6,5,4,4,5,5,5,3,NaN,...,5,5,NaN,5,6,NaN,5,NaN,5,5
16,Q16,6,4,5,5,6,4,5,1,5,...,5,5,5,6,6,6,5,5,6,1
17,Q17,6,4,4,5,5,5,5,6,5,...,4,6,5,5,6,5,5,6,6,6
18,Q18,6,4,5,6,5,5,4,6,6,...,6,6,6,5,6,6,5,5,6,4
19,Q19,6,5,5,5,5,5,4,6,5,...,5,6,5,5,6,5,5,6,6,5
20,Q20,6,4,5,4,4,4,NaN,6,4,...,5,6,4,4,6,5,5,6,5,6
21,Q21,6,5,5,5,5,5,5,6,6,...,6,6,6,6,4,6,5,6,5,6
22,Q22,6,5,5,4,5,5,4,6,5,...,5,6,5,4,6,NaN,5,5,6,6
23,Q23,6,5,5,6,6,6,4,6,6,...,5,6,4,6,6,5,5,6,6,6
24,Q24,6,3,5,5,4,4,4,1,6,...,5,NaN,NaN,5,6,NaN,5,6,4,5
25,Q25,5,3,4,4,5,3,4,4,3,...,4,4,3,4,5,4,4,5,5,6
26,Q26,6,5,5,5,5,6,5,4,6,...,5,6,5,4,6,4,5,6,6,6
27,Q27,6,5,5,5,4,5,5,4,4,...,5,4,4,4,6,5,5,5,6,6
28,Q28,6,4,5,6,4,6,5,4,5,...,5,6,4,5,6,6,5,5,6,6
29,Q29,4,3,4,4,4,4,4,4,2,...,4,3,3,4,4,5,5,4,5,6
30,Q31,6,4,5,NaN,4,NaN,NaN,4,NaN,...,5,NaN,NaN,3,4,4,5,5,5,6
31,Q32,6,5,5,NaN,5,NaN,NaN,5,NaN,...,5,NaN,NaN,5,5,5,5,4,5,6
32,Q33,6,5,5,NaN,5,NaN,NaN,5,NaN,...,5,NaN,NaN,5,4,5,5,3,5,6
33,Q34,6,4,5,NaN,4,NaN,NaN,5,NaN,...,5,NaN,NaN,4,5,4,5,5,6,6
34,Q35,6,4,5,NaN,5,NaN,NaN,5,NaN,...,5,NaN,NaN,4,5,4,5,5,6,6
35,Q36,6,4,2,NaN,5,NaN,NaN,2,NaN,...,3,NaN,NaN,4,4,5,5,4,4,6

In [133]:
# drop the row of gender
data = data.drop([0],axis=0)

In [134]:
# drop 題號
dat = data.drop('number', axis = 1)

In [135]:
dat

,1,2,3,4,5,6,7,8,9,10,...,272,273,274,275,276,277,278,279,280,281
1,3,3,2,3,4,3,4,3,1,2,...,5,4,NaN,4,5,4,4,5,3,4
2,6,5,5,6,5,5,5,6,4,4,...,5,6,4,5,4,6,4,5,6,6
3,6,5,5,6,5,5,4,6,5,5,...,6,6,5,5,2,5,5,6,5,6
4,6,5,5,6,5,4,5,6,5,5,...,6,6,6,6,2,6,6,6,6,6
5,6,5,5,6,6,5,4,6,5,5,...,6,6,4,6,6,6,5,5,5,6
6,6,4,5,5,4,5,4,6,2,6,...,6,6,5,5,6,6,5,4,6,6
7,4,4,4,3,3,5,4,1,1,3,...,5,3,4,4,5,4,4,2,3,6
8,6,2,4,5,4,4,4,1,1,3,...,4,3,5,4,5,3,3,2,4,3
9,6,5,4,5,3,4,4,6,2,4,...,5,5,4,3,4,6,5,4,5,6
10,6,4,5,6,4,4,5,4,NaN,4,...,5,3,5,5,NaN,5,6,6,6,6
11,6,3,4,5,5,3,4,4,5,5,...,4,NaN,NaN,5,6,2,5,NaN,5,3
12,6,3,5,6,5,5,5,4,5,5,...,6,6,5,5,5,5,5,6,6,6
13,6,5,5,5,5,5,4,6,5,4,...,5,6,5,6,6,6,5,6,6,6
14,6,5,5,5,5,5,5,6,6,4,...,6,6,6,6,6,4,5,6,6,6
15,6,5,4,4,5,5,5,3,NaN,5,...,5,5,NaN,5,6,NaN,5,NaN,5,5
16,6,4,5,5,6,4,5,1,5,4,...,5,5,5,6,6,6,5,5,6,1
17,6,4,4,5,5,5,5,6,5,5,...,4,6,5,5,6,5,5,6,6,6
18,6,4,5,6,5,5,4,6,6,6,...,6,6,6,5,6,6,5,5,6,4
19,6,5,5,5,5,5,4,6,5,4,...,5,6,5,5,6,5,5,6,6,5
20,6,4,5,4,4,4,NaN,6,4,4,...,5,6,4,4,6,5,5,6,5,6
21,6,5,5,5,5,5,5,6,6,5,...,6,6,6,6,4,6,5,6,5,6
22,6,5,5,4,5,5,4,6,5,4,...,5,6,5,4,6,NaN,5,5,6,6
23,6,5,5,6,6,6,4,6,6,4,...,5,6,4,6,6,5,5,6,6,6
24,6,3,5,5,4,4,4,1,6,5,...,5,NaN,NaN,5,6,NaN,5,6,4,5
25,5,3,4,4,5,3,4,4,3,4,...,4,4,3,4,5,4,4,5,5,6
26,6,5,5,5,5,6,5,4,6,4,...,5,6,5,4,6,4,5,6,6,6
27,6,5,5,5,4,5,5,4,4,4,...,5,4,4,4,6,5,5,5,6,6
28,6,4,5,6,4,6,5,4,5,5,...,5,6,4,5,6,6,5,5,6,6
29,4,3,4,4,4,4,4,4,2,3,...,4,3,3,4,4,5,5,4,5,6
30,6,4,5,NaN,4,NaN,NaN,4,NaN,4,...,5,NaN,NaN,3,4,4,5,5,5,6
31,6,5,5,NaN,5,NaN,NaN,5,NaN,4,...,5,NaN,NaN,5,5,5,5,4,5,6
32,6,5,5,NaN,5,NaN,NaN,5,NaN,4,...,5,NaN,NaN,5,4,5,5,3,5,6
33,6,4,5,NaN,4,NaN,NaN,5,NaN,4,...,5,NaN,NaN,4,5,4,5,5,6,6
34,6,4,5,NaN,5,NaN,NaN,5,NaN,2,...,5,NaN,NaN,4,5,4,5,5,6,6
35,6,4,2,NaN,5,NaN,NaN,2,NaN,5,...,3,NaN,NaN,4,4,5,5,4,4,6

In [142]:
# select particular items
Q16 = dat.iloc[15,:]
Q17 = dat.iloc[16,:]
Q18 = dat.iloc[17,:]
Q19 = dat.iloc[18,:]
Q20 = dat.iloc[19,:]

In [143]:
Q16

1      6
2      4
3      5
4      5
5      6
      ..
277    6
278    5
279    5
280    6
281    1
Name: 16, Length: 281, dtype: object

In [144]:
# check for NA
print('the number of NA for Q16 is',Q16.isnull().sum())
print('the number of NA for Q17 is',Q17.isnull().sum())
print('the number of NA for Q18 is',Q18.isnull().sum())
print('the number of NA for Q19 is',Q19.isnull().sum())
print('the number of NA for Q20 is',Q20.isnull().sum())

the number of NA for Q16 is 3
the number of NA for Q17 is 3
the number of NA for Q18 is 1
the number of NA for Q19 is 3
the number of NA for Q20 is 4

In [145]:
dat_int = dat.fillna(-1).to_numpy()

In [146]:
dat_int

array([['3', '3', '2', ..., '5', '3', '4'],
       ['6', '5', '5', ..., '5', '6', '6'],
       ['6', '5', '5', ..., '6', '5', '6'],
       ...,
       ['6', '4', '5', ..., '5', '6', '6'],
       ['6', '4', '5', ..., '5', '6', '6'],
       ['6', '4', '2', ..., '4', '4', '6']], dtype=object)

In [150]:
dat_int = dat_int.astype(int)

In [152]:
dat_int

array([[3, 3, 2, ..., 5, 3, 4],
       [6, 5, 5, ..., 5, 6, 6],
       [6, 5, 5, ..., 6, 5, 6],
       ...,
       [6, 4, 5, ..., 5, 6, 6],
       [6, 4, 5, ..., 5, 6, 6],
       [6, 4, 2, ..., 4, 4, 6]])

In [151]:
for i in dat_int:
    for j in dat_int[i]:
        if i == -1:
        i = 'NaN'

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [67]:
# mean imputation
Q16_mean = np.nanmean(Q16)   
X_imputed_by_mean = np.where(np.isnan(X), Age_mean, X)

TypeError: can only concatenate str (not "int") to str

# Descriptive statistics

<ul>
<li>A. 情緒性支持：Q16, Q18</li>
<li>B. 工具性支持：Q19</li>
<li>C. 訊息性支持：Q17, Q20</li>
</ul>

## 平均數

In [38]:
Q16_mean =

SyntaxError: invalid syntax (<ipython-input-38-a4aff34d11b0>, line 1)